### ISSUE TITLE
`skyplane replicate-random` doesn't work

### ISSUE THREAD

**Issue by samkumar** [skyplane-project/skyplane#439]
This is the output I got (on `27bc24b08ed6da1ba2afaaeb82010aa44fc48b3f`, which is the commit currently at the head of the `main` branch):
```
$ skyplane replicate-random azure:westus2 azure:eastus -n 1 -s $((1024 * 68)) --chunk-size-mb 68
 _____ _   ____   _______ _       ___   _   _  _____ 
/  ___| | / /\ \ / / ___ \ |     / _ \ | \ | ||  ___|
\ `--.| |/ /  \ V /| |_/ / |    / /_\ \|  \| || |__  
 `--. \    \   \ / |  __/| |    |  _  || . ` ||  __| 
/\__/ / |\  \  | | | |   | |____| | | || |\  || |___ 
\____/\_| \_/  \_/ \_|   \_____/\_| |_/\_| \_/\____/


Will transfer 1024 objects totaling 68.00GB from azure:westus2 to azure:eastus
    VMs to provision: 1x azure:eastus, 1x azure:westus2

Using overridden docker image: 
ghcr.io/skyplane-project/skyplane:local-18ef01fd32a2afb9b5a39059c49e174f
Storing debug information for transfer in /tmp/skyplane/transfer_logs/20220629_165357/client.log
✓ Initializing cloud keys (2/2) in 3.88s
✓ Provisioning gateway instances (2/2) in 98.65s
✓ Installing gateway package (2/2) in 38.20s
Traceback (most recent call last):
  File "/home/sam/Documents/Research/skylark/skyplane-venv/bin/skyplane", line 8, in <module>
    sys.exit(app())
  File "/home/sam/Documents/Research/skylark/skyplane-venv/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/sam/Documents/Research/skylark/skyplane-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/Documents/Research/skylark/skyplane-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sam/Documents/Research/skylark/skyplane-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sam/Documents/Research/skylark/skyplane-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/Documents/Research/skylark/skyplane-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/Documents/Research/skylark/skyplane-venv/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/sam/Documents/Research/skylark/skylark/skyplane/cli/cli_internal.py", line 69, in replicate_random
    stats = launch_replication_job(
  File "/home/sam/Documents/Research/skylark/skylark/skyplane/cli/cli_impl/cp_replicate.py", line 238, in launch_replication_job
    job = rc.run_replication_plan(
  File "/home/sam/Documents/Research/skylark/skylark/skyplane/replicate/replicator_client.py", line 308, in run_replication_plan
    assign_jobs.append(partial(gateway.authorize_storage_account, job.source_bucket.split("/", 1)[0]))
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by parasj** [comment]
The `authorize_storage_account` method has been removed, so this issue shouldn't occur now.
