### ISSUE TITLE
S3 -> S3 transfer fails with `MissingObjectException`

### ISSUE THREAD

**Issue by romilbhardwaj** [skyplane-project/skyplane#490]
Continuing the slack conversation here -

I am trying to do a S3 -> S3 transfer between two buckets I created:

```
$ skyplane cp --recursive s3://romil-sky-test/ s3://romil-dataset
 _____ _   ____   _______ _       ___   _   _  _____
/  ___| | / /\ \ / / ___ \ |     / _ \ | \ | ||  ___|
\ `--.| |/ /  \ V /| |_/ / |    / /_\ \|  \| || |__
 `--. \    \   \ / |  __/| |    |  _  || . ` ||  __|
/\__/ / |\  \  | | | |   | |____| | | || |\  || |___
\____/\_| \_/  \_/ \_|   \_____/\_| |_/\_| \_/\____/

Traceback (most recent call last):
  File "/home/romilb/repos/skyplane/skyplane/cli/cli.py", line 121, in cp
    src_region, bucket_src, path_src, dst_region, bucket_dst, path_dst, recursive=recursive
  File "/home/romilb/repos/skyplane/skyplane/cli/cli_impl/cp_replicate.py", line 145, in
generate_full_transferobjlist
    dest_key = map_object_key_prefix(source_prefix, source_obj.key, dest_prefix, recursive=recursive)
  File "/home/romilb/repos/skyplane/skyplane/cli/cli_impl/cp_replicate.py", line 109, in
map_object_key_prefix
    raise exceptions.MissingObjectException(f"Source key {source_key} does not start with source prefix
{source_prefix}")
skyplane.exceptions.MissingObjectException: Source key sky.prof does not start with source prefix /

❌ MissingObjectException: Source key sky.prof does not start with source prefix /
Please ensure that the object exists and is accessible.
```

Here's the source bucket and it's contents:
![image](https://user-images.githubusercontent.com/4416605/184048029-e2de5b01-2176-4dc1-82ef-857d26270667.png)

I've tried variations with and without a trailing slash (`/`) and the `--recursive` flag, but I get the same error. What's a good way to debug this? 

I'm on commit `e8eabe9e44cfbbef035c183c989c32471228fa1c`

**Comment by parasj** [comment]
I just tested #487 which should have a fix:

```
$ skyplane cp s3://skylark-test-us-east-1/ s3://skyplane-demo-us-east-1 --recursive
 _____ _   ____   _______ _       ___   _   _  _____ 
/  ___| | / /\ \ / / ___ \ |     / _ \ | \ | ||  ___|
\ `--.| |/ /  \ V /| |_/ / |    / /_\ \|  \| || |__  
 `--. \    \   \ / |  __/| |    |  _  || . ` ||  __| 
/\__/ / |\  \  | | | |   | |____| | | || |\  || |___ 
\____/\_| \_/  \_/ \_|   \_____/\_| |_/\_| \_/\____/


Will transfer 5 objects totaling 128.88MB from aws:us-east-1 to aws:us-east-1
    VMs to provision: 1x aws:us-east-1
    out/cost.csv => out/cost.csv
    test.txt => test.txt
    test_dir => test_dir
    test_dir/cost.csv => test_dir/cost.csv
    ...
    test_dir1 => test_dir1
Continue? [Y/n]: Y
Transfer starting (Tip: Enable auto-confirmation with `skyplane config set autoconfirm true`)

Storing debug information for transfer in /tmp/skyplane/transfer_logs/20220811_030813/client.log
✓ Initializing cloud keys (3/3) in 1.80s
✓ Provisioning gateway instances (1/1) in 28.02s
✓ Installing gateway package (1/1) in 21.64s
🚀 0.13GB transfer job launched
  Transfer progress (20 of 20 chunks) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.9/128.9 MiB 229.9 MB/s 0:00:00
✓ Deprovisioning instances (1/1) in 1.18s

✅ Transfer completed successfully
Transfer runtime: 1.34s, Throughput: 0.75Gbps
⠸ Verifying all files were copied
```

**Comment by romilbhardwaj** [comment]
Yep! Can confirm, #487 fixes this. Thanks!
