### ISSUE TITLE
Error on `skyplane init` for azure 

### ISSUE THREAD

**Issue by sarahwooders** [skyplane-project/skyplane#524]
## Repro Instructions 
I ran `skyplane init`. I pressed `enter` instead of `Y/n` for the CLI promps. For AWS, this loaded the default AWS credentials, but for Azure, an error trace printed. 

## Error Log 
```
 _____ _   ____   _______ _       ___   _   _  _____
/  ___| | / /\ \ / / ___ \ |     / _ \ | \ | ||  ___|
\ `--.| |/ /  \ V /| |_/ / |    / /_\ \|  \| || |__
 `--. \    \   \ / |  __/| |    |  _  || . ` ||  __|
/\__/ / |\  \  | | | |   | |____| | | || |\  || |___
\____/\_| \_/  \_/ \_|   \_____/\_| |_/\_| \_/\____/

17:23:31 [DEBUG] Found existing configuration file at /Users/sarahwooders/.skyplane/config, loading

(1) Configuring AWS:
    Do you want to configure AWS support in Skyplane? [Y/n]:
    Loaded AWS credentials from the AWS CLI [IAM access key ID: ...XP4ETK]
    AWS region config file saved to /Users/sarahwooders/.skyplane/aws_config

(2) Configuring Azure:
    Do you want to configure Azure support in Skyplane? [Y/n]:
Traceback (most recent call last):
  File "/Users/sarahwooders/repos/skyplane/env/bin/skyplane", line 33, in <module>
    sys.exit(load_entry_point('skyplane', 'console_scripts', 'skyplane')())
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sarahwooders/repos/skyplane/env/lib/python3.7/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/sarahwooders/repos/skyplane/skyplane/cli/cli.py", line 516, in init
    cloud_config = load_azure_config(cloud_config, force_init=reinit_azure, non_interactive=non_interactive)
  File "/Users/sarahwooders/repos/skyplane/skyplane/cli/cli_impl/init.py", line 100, in load_azure_config
    or AzureAuthentication.infer_subscription_id(),
  File "/Users/sarahwooders/repos/skyplane/skyplane/compute/azure/azure_auth.py", line 157, in infer_subscription_id
    return subprocess.check_output(["az", "account", "show", "--query", "id"]).decode("utf-8").replace('"', "").strip()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'az': 'az'
```

**Comment by parasj** [comment]
@abiswal2001 Please take a look at this

**Comment by parasj** [comment]
This error looks like you don't have the Azure CLI installed, can you run `which az`?

**Comment by abiswal2001** [comment]
Yes, azure init is running cli commands to create credentials so if the cli isn't installed a bug will occur. I can clean this up and print a more clear message to indicate as such @parasj ?

**Comment by parasj** [comment]
That's a reasonable plan. I think we should set it up to quickly check if the `az` CLI is installed during init if the user opts for the automated setup.

I pushed a quick PR for this here: https://github.com/skyplane-project/skyplane/pull/567
