### ISSUE TITLE
ValueError while running 1M file transfer

### ISSUE THREAD

**Issue by antonzabreyko** [skyplane-project/skyplane#541]
When running a transfer job consisting of one million files, the following error occurs:

`Storing debug information for transfer in /tmp/skyplane/transfer_logs/20220915_003039/client.log
✓ Initializing cloud keys (5/5) in 4.47s
✓ Provisioning gateway instances (2/2) in 35.42s
✓ Installing gateway package (2/2) in 13.49s
🚀 0.00GB transfer job launched
⠏ Transfer progress (67655 of 1000000 chunks) ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.1/976.6 KiB ? -:--:--
Compression saved -2300.00% of egress fees
✓ Deprovisioning instances (2/2) in 2.70s

❌ AWSServer(region_tag=aws:us-west-2, instance_id=i-0a2071ce582135eff) encountered error:
Traceback (most recent call last):
  File "/pkg/skyplane/gateway/gateway_sender.py", line 95, in worker_loop
    self.send_chunks([next_chunk_id], dest_ip)
  File "/pkg/skyplane/gateway/gateway_sender.py", line 184, in send_chunks
    self.chunk_store.state_start_upload(chunk_id, f"sender:{self.worker_id}")
  File "/pkg/skyplane/gateway/chunk_store.py", line 93, in state_start_upload
    raise ValueError(f"Invalid transition start_upload from {state} (id={chunk_id})")
ValueError: Invalid transition start_upload from ChunkState.downloaded (id=327334)
`

It appears this error non-deterministically happens, as previously it occurred at roughly 300 KiB transferred.

**Comment by parasj** [comment]
To update state on this PR, @antonzabreyko and I discussed two mitigations:
1. Testing the gateway with a less than check on chunk status instead of an equality check. Ideally, we print an error on state mismatches to count how many chunks encounter a status inconsistency.
2. A more intensive mitigation involving replacing the ChunkStore status log with per-thread state that is not shared (i.e. store state in queues). The ChunkStore would then retain a single dict that contains the set of chunks that have completed rather than a granular log.

**Comment by sarahwooders** [comment]
Is this still an issue?

**Comment by parasj** [comment]
Yeah, this is still a pretty major issue. We can close this when we migrate to the ChunkStore-free gateway but that hasn't been integrated yet. The issue is that the manager cannot keep up with high QPS with many chunks.

**Comment by antonzabreyko** [comment]
I can issue a quick patch that slackens the state check if it's needed before the ChunkStore is removed. Just let me know.

**Comment by parasj** [comment]
Let's wait until the ChunkStore free gateway code is merged (Sarah is working on this) and then @antonzabreyko should retest that code to see if the issue persists.
