### ISSUE TITLE
[bug] Unknown parameter in input: "KeyType", must be one of: KeyName, DryRun, TagSpecifications

### ISSUE THREAD

**Issue by ephemer** [skyplane-project/skyplane#783]
**Describe the bug**
I am trying to transfer a prefix of one bucket on GCP to the same prefix on an S3 bucket.

**To Reproduce**
Steps to reproduce the behavior (please include the full Skyplane command you ran):
1. `pip install skyplane[aws,gcp]` note: this is 0.21. It fails in the same way with `skyplane-dev[aws,gcp]` (0.30)
2. `skyplane init`
3. skyplane cp --recursive gs://my_bucket/targets/dirpath/ s3://my-bucket/targets/dirpath/
4. I get a list of files to transfer and can confirm `[Y/n]` -> `y [enter]`

> Configuring AWS regions ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1 0:00:0218:05:45 [ERROR] Error running setup_region: Parameter validation
> failed:
> Unknown parameter in input: "KeyType", must be one of: KeyName,
> DryRun, TagSpecifications

**Expected behavior**
I can transfer files

**Transfer client log**

```
18:04:57 [INFO]  [SkyplaneClient.direct_dataplane] Topology: {"replication_topology_edges": [{"src": {"type": "ReplicationTopologyObjectStore", "fields": {"region": "gcp:us-west1-b"}}, "dest": {"type": "ReplicationTopologyGateway", "fields": {"region": "gcp:us-west1-b", "instance": 0}}, "num_connections": 0}, {"src": {"type": "ReplicationTopologyGateway", "fields": {"region": "gcp:us-west1-b", "instance": 0}}, "dest": {"type": "ReplicationTopologyGateway", "fields": {"region": "aws:eu-west-1", "instance": 0}}, "num_connections": 32}, {"src": {"type": "ReplicationTopologyGateway", "fields": {"region": "aws:eu-west-1", "instance": 0}}, "dest": {"type": "ReplicationTopologyObjectStore", "fields": {"region": "aws:eu-west-1"}}, "num_connections": 0}]}
18:04:57 [DEBUG] Using dataplane: <skyplane.api.dataplane.Dataplane object at 0x160d52820>
18:04:57 [INFO]  [SkyplaneClient.direct_dataplane] Topology: {"replication_topology_edges": [{"src": {"type": "ReplicationTopologyObjectStore", "fields": {"region": "gcp:us-west1-b"}}, "dest": {"type": "ReplicationTopologyGateway", "fields": {"region": "gcp:us-west1-b", "instance": 0}}, "num_connections": 0}, {"src": {"type": "ReplicationTopologyGateway", "fields": {"region": "gcp:us-west1-b", "instance": 0}}, "dest": {"type": "ReplicationTopologyGateway", "fields": {"region": "aws:eu-west-1", "instance": 0}}, "num_connections": 32}, {"src": {"type": "ReplicationTopologyGateway", "fields": {"region": "aws:eu-west-1", "instance": 0}}, "dest": {"type": "ReplicationTopologyObjectStore", "fields": {"region": "aws:eu-west-1"}}, "num_connections": 0}]}
18:04:57 [DEBUG] Using dataplane: <skyplane.api.dataplane.Dataplane object at 0x160d52bb0>
18:04:57 [DEBUG] [SkyplaneClient] Queued copy job CopyJob(src_path='gs://note_detection_data/targets/targets_maestro_22050_nooverlap/', dst_path='s3://note-detection-data/targets/targets_maestro_22050_nooverlap/', recursive=True, requester_pays=False, uuid='60285000-fc3a-46c1-9452-548b295dc414', transfer_list=[], multipart_transfer_list=[])
18:05:00 [DEBUG] Generating transfer pairs for external access, <skyplane.obj_store.gcs_interface.GCSInterface object at 0x160d52a90> -> <skyplane.obj_store.s3_interface.S3Interface object at 0x1611ba6a0>
18:05:01 [DEBUG] Querying objects in gs://note_detection_data
18:05:02 [DEBUG] Generating transfer pairs for external access, <skyplane.obj_store.gcs_interface.GCSInterface object at 0x160d52a90> -> <skyplane.obj_store.s3_interface.S3Interface object at 0x1611ba6a0>
18:05:02 [DEBUG] Querying objects in gs://note_detection_data
18:05:25 [DEBUG] User confirmed transfer
18:05:25 [INFO]  [Provisioner.add_task] Queue ProvisionerTask(cloud_provider='aws', region='eu-west-1', vm_type='m5.8xlarge', spot=False, autoterminate_minutes=15, tags={'skyplane': 'true', 'skyplaneclientid': '00000000000000000000f2e7a47119ef'}, uuid='fe27e200-1d69-46f7-92c7-b46918d34a30')
18:05:25 [INFO]  [Provisioner.add_task] Queue ProvisionerTask(cloud_provider='gcp', region='us-west1-b', vm_type='n2-standard-32', spot=False, autoterminate_minutes=15, tags={'skyplane': 'true', 'skyplaneclientid': '00000000000000000000f2e7a47119ef'}, uuid='4676ef1c-3326-4b06-b215-8ac902e577e9')
18:05:25 [INFO]  [Provisioner.init_global] Initializing global resources for aws=True, azure=False, gcp=True
18:05:32 [DEBUG] Updating firewall rule skyplane-default-allow-internal
18:05:38 [DEBUG] Updating firewall rule skyplane-default-allow-ssh
18:05:43 [DEBUG] Updating firewall rule skyplane-default-allow-icmp
18:05:45 [DEBUG] [aws_network]:eu-west-1 Found existing rule for 0.0.0.0/0:22 in skyplane, not adding again
18:05:45 [DEBUG] [AWS] Creating keypair skyplane-00000000000000000000f2e7a47119ef-eu-west-1 in eu-west-1
18:05:45 [ERROR] Error running setup_region: Parameter validation failed:
Unknown parameter in input: "KeyType", must be one of: KeyName, DryRun, TagSpecifications
18:05:45 [ERROR] Exception: Parameter validation failed:
Unknown parameter in input: "KeyType", must be one of: KeyName, DryRun, TagSpecifications
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/cli/cli_transfer.py", line 382, in cp
    dp.provision(spinner=True)
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/api/dataplane.py", line 131, in provision
    uuids = self.provisioner.provision(
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/api/provisioner.py", line 198, in provision
    do_parallel(
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/utils/fn.py", line 57, in do_parallel
    args, result = future.result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/utils/fn.py", line 43, in wrapped_fn
    return args, func(args)
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/compute/aws/aws_cloud_provider.py", line 81, in setup_region
    self.key_manager.ensure_key_exists(region, f"{self.key_prefix}-{region}")
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/compute/aws/aws_key_manager.py", line 70, in ensure_key_exists
    return self.make_key(aws_region, key_name)
  File "/opt/homebrew/lib/python3.9/site-packages/skyplane/compute/aws/aws_key_manager.py", line 42, in make_key
    key_pair = ec2.create_key_pair(KeyName=key_name, KeyType="rsa")
  File "/opt/homebrew/lib/python3.9/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/opt/homebrew/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/homebrew/lib/python3.9/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/homebrew/lib/python3.9/site-packages/botocore/validate.py", line 293, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "KeyType", must be one of: KeyName, DryRun, TagSpecifications
18:05:46 [WARN]  Attempting to deprovision dataplane that is not provisioned, this may be from auto_deprovision.
18:05:46 [WARN]  Deprovisioning dataplane
18:05:46 [WARN]  Attempting to deprovision dataplane that is not provisioned, this may be from auto_deprovision.
```

**Environment info (please complete the following information):**
 - OS: Mac OS
- Python version 3.9

**Comment by ephemer** [comment]
Never mind, since this was a crash in `botocore` I ran `pip install --upgrade botocore` and it seems to be running now
