### ISSUE TITLE
[bug] azure package is deprecated

### ISSUE THREAD

**Issue by eyalzo** [skyplane-project/skyplane#910]
**Describe the bug**
The azure package is deprecated. Need ti install individual packages.

**To Reproduce**
Steps to reproduce the behavior (please include the full Skyplane command you ran):
1. Run 'pip install azure'
2. See error

**Expected behavior**

**Screenshots**
% pip install azure
Collecting azure
  Downloading azure-5.0.0.zip (4.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/72/tm0y9z7s5ps7czwbhk3b3rwm0000gn/T/pip-install-9bbpxnbf/azure_e8b7dcef3e364884b5509ff05e7da165/setup.py", line 60, in <module>
          raise RuntimeError(message)
      RuntimeError:
      
      Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.
      
      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all
      
      Here's a non-exhaustive list of common packages:
      
      -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
      -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
      -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
      -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
      -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts
      
      A more comprehensive discussion of the rationale for this decision can be found in the following issue:
      https://github.com/Azure/azure-sdk-for-python/issues/10646

**Transfer client log**

None.

**Environment info (please complete the following information):**
 - OS: Mac OS
- Python version: 3.11.2
- Skyplane version : 3.2.2

**Additional context**

Needed only when using Azure.

**Comment by eyalzo** [comment]
Note that this fix is not enough - https://github.com/skyplane-project/skyplane/commit/2aab284a80943871c8c4cc9e25ccde7eec063831
This is because the same should be fixed in the main README.
