### ISSUE TITLE
Azure copy doesn't work [bug] 

### ISSUE THREAD

**Issue by maciej-wolny** [skyplane-project/skyplane#918]
**Describe the bug**
While trying to copy data from an Azure account to S3 bucket I'm getting Storage account xxx not found error followed by KeyError: 'Invalid flag: default_azure_region'. The account is visible while doing `az storage list accounts`, also the flag for a default region was set using `skyplane config set azure_default_region` but it didn't fix the issue. 

**To Reproduce**
- Install skyplane
- Install aws, azure-cli
- Authenticate clis: `azure login`
- Skyplane init
- skyplane cp azure s3

**Expected behavior**
The copy doesn't even start

**Transfer client log**
```
 skyplane cp -r "https://account.blob.core.windows.net/datastore" s3://datastore/ --debug
 _____ _   ____   _______ _       ___   _   _  _____ 
/  ___| | / /\ \ / / ___ \ |     / _ \ | \ | ||  ___|
\ `--.| |/ /  \ V /| |_/ / |    / /_\ \|  \| || |__  
 `--. \    \   \ / |  __/| |    |  _  || . ` ||  __| 
/\__/ / |\  \  | | | |   | |____| | | || |\  || |___ 
\____/\_| \_/  \_/ \_|   \_____/\_| |_/\_| \_/\____/

17:24:42 [ERROR] Exception: Storage account lanzaideliveries not found
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/skyplane/obj_store/azure_storage_account_interface.py", line 29, in azure_region
    return self.storage_account_obj().location
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/skyplane/obj_store/azure_storage_account_interface.py", line 23, in storage_account_obj
    raise exceptions.MissingBucketException(f"Storage account {self.account_name} not found")
skyplane.exceptions.MissingBucketException: Storage account account not found
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/homebrew/lib/python3.11/site-packages/skyplane/obj_store/azure_storage_account_interface.py │
│ :29 in azure_region                                                                              │
│                                                                                                  │
│   26 │   def azure_region(self):                                                                 │
│   27 │   │   """Return the Azure region of the storage account. If the user doesn't have acce    │
│   28 │   │   try:                                                                                │
│ ❱ 29 │   │   │   return self.storage_account_obj().location                                      │
│   30 │   │   except Exception as e:  # user does not have "Storage Account Contributor" role     │
│   31 │   │   │   logger.exception(e)                                                             │
│   32 │   │   │   return cloud_config.get_flag("default_azure_region")                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ self = <skyplane.obj_store.azure_storage_account_interface.AzureStorageAccountInterface      │ │
│ │        object at 0x146d6c250>                                                                │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/skyplane/obj_store/azure_storage_account_interface.py │
│ :23 in storage_account_obj                                                                       │
│                                                                                                  │
│   20 │   │   for storage_account in storage_accounts:                                            │
│   21 │   │   │   if storage_account.name == self.account_name:                                   │
│   22 │   │   │   │   return storage_account                                                      │
│ ❱ 23 │   │   raise exceptions.MissingBucketException(f"Storage account {self.account_name} no    │
│   24 │                                                                                           │
│   25 │   @property                                                                               │
│   26 │   def azure_region(self):                                                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │             self = <skyplane.obj_store.azure_storage_account_interface.AzureStorageAccountI… │ │
│ │                    object at 0x146d6c250>                                                    │ │
│ │        sm_client = <azure.mgmt.storage._storage_management_client.StorageManagementClient    │ │
│ │                    object at 0x146d6f290>                                                    │ │
│ │  storage_account = <azure.mgmt.storage.v2022_09_01.models._models_py3.StorageAccount object  │ │
│ │                    at 0x1474d1f90>                                                           │ │
│ │ storage_accounts = <iterator object azure.core.paging.ItemPaged at 0x1470ef450>              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
MissingBucketException: Storage account account not found

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/homebrew/lib/python3.11/site-packages/skyplane/cli/cli_transfer.py:462 in cp                │
│                                                                                                  │
│   459 │   :param solver: The solver to use for the transfer (default: direct)                    │
│   460 │   :type solver: str                                                                      │
│   461 │   """                                                                                    │
│ ❱ 462 │   return run_transfer(src, dst, recursive, debug, multipart, confirm, max_instances, m   │
│   463                                                                                            │
│   464                                                                                            │
│   465 def sync(                                                                                  │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                          confirm = False                                                     │ │
│ │                            debug = True                                                      │ │
│ │                              dst = 's3://hs-research-cello/'                                 │ │
│ │                  max_connections = 32                                                        │ │
│ │                    max_instances = 1                                                         │ │
│ │                        multipart = True                                                      │ │
│ │                        recursive = True                                                      │ │
│ │                           solver = 'direct'                                                  │ │
│ │ solver_required_throughput_gbits = 1.0                                                       │ │
│ │                              src = 'https://account.blob.core.windows.net/datastore… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/skyplane/cli/cli_transfer.py:328 in run_transfer      │
│                                                                                                  │
│   325 │   elif provider_dst == "cloudflare":                                                     │
│   326 │   │   solver = "src_one_sided"                                                           │
│   327 │                                                                                          │
│ ❱ 328 │   src_region_tag = StorageInterface.create(f"{provider_src}:infer", bucket_src).region   │
│   329 │   dst_region_tag = StorageInterface.create(f"{provider_dst}:infer", bucket_dst).region   │
│   330 │   args = {                                                                               │
│   331 │   │   "cmd": cmd,                                                                        │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │      bucket_dst = 'datastore'                                                        │ │
│ │      bucket_src = 'account/container │ │
│ │             cmd = 'cp'                                                                       │ │
│ │         confirm = False                                                                      │ │
│ │           debug = True                                                                       │ │
│ │             dst = 's3://datastore/'                                                  │ │
│ │ max_connections = 32                                                                         │ │
│ │   max_instances = 1                                                                          │ │
│ │       multipart = True                                                                       │ │
│ │        path_dst = ''                                                                         │ │
│ │        path_src = ''                                                                         │ │
│ │    provider_dst = 'aws'                                                                      │ │
│ │    provider_src = 'azure'                                                                    │ │
│ │       recursive = True                                                                       │ │
│ │          solver = 'direct'                                                                   │ │
│ │             src = 'https://account.blob.core.windows.net/datastore│ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/skyplane/obj_store/azure_blob_interface.py:41 in      │
│ region_tag                                                                                       │
│                                                                                                  │
│    38 │   │   return f"https://{self.account_name}.blob.core.windows.net/{self.container_name}   │
│    39 │                                                                                          │
│    40 │   def region_tag(self):                                                                  │
│ ❱  41 │   │   return f"azure:{self.storage_account_interface.azure_region}"                      │
│    42 │                                                                                          │
│    43 │   def bucket(self) -> str:                                                               │
│    44 │   │   return f"{self.account_name}/{self.container_name}"                                │
│                                                                                                  │
│ ╭───────────────────────────────────────── locals ──────────────────────────────────────────╮    │
│ │ self = <skyplane.obj_store.azure_blob_interface.AzureBlobInterface object at 0x13327d550> │    │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────╯    │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/skyplane/obj_store/azure_storage_account_interface.py │
│ :32 in azure_region                                                                              │
│                                                                                                  │
│   29 │   │   │   return self.storage_account_obj().location                                      │
│   30 │   │   except Exception as e:  # user does not have "Storage Account Contributor" role     │
│   31 │   │   │   logger.exception(e)                                                             │
│ ❱ 32 │   │   │   return cloud_config.get_flag("default_azure_region")                            │
│   33 │                                                                                           │
│   34 │   @property                                                                               │
│   35 │   def storage_management_client(self):                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ self = <skyplane.obj_store.azure_storage_account_interface.AzureStorageAccountInterface      │ │
│ │        object at 0x146d6c250>                                                                │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/skyplane/config.py:322 in get_flag                    │
│                                                                                                  │
│   319 │                                                                                          │
│   320 │   def get_flag(self, flag_name):                                                         │
│   321 │   │   if flag_name not in self.valid_flags():                                            │
│ ❱ 322 │   │   │   raise KeyError(f"Invalid flag: {flag_name}")                                   │
│   323 │   │   return getattr(self, f"flag_{flag_name}", _DEFAULT_FLAGS[flag_name])               │
│   324 │                                                                                          │
│   325 │   def set_flag(self, flag_name, value: Optional[Any]):                                   │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ────────────────────────────────────╮                │
│ │ flag_name = 'default_azure_region'                                            │                │
│ │      self = SkyplaneConfig(                                                   │                │
│ │             │   aws_enabled=True,                                             │                │
│ │             │   azure_enabled=False,                                          │                │
│ │             │   gcp_enabled=False,                                            │                │
│ │             │   cloudflare_enabled=False,                                     │                │
│ │             │   ibmcloud_enabled=False,                                       │                │
│ │             │   anon_clientid='00000000000000000000125140e9589c',             │                │
│ │             │   azure_principal_id='93105b18-d76c-4da5-8fce-cbcef5f42cd4',    │                │
│ │             │   azure_subscription_id='b153161a-9edf-4bf2-99fa-eed283a99834', │                │
│ │             │   azure_resource_group='skyplane',                              │                │
│ │             │   azure_umi_name='skyplane_umi',                                │                │
│ │             │   azure_client_id='7fd47b3d-88e5-403e-b3e7-b7b3cd41bd28',       │                │
│ │             │   cloudflare_access_key_id=None,                                │                │
│ │             │   cloudflare_secret_access_key=None,                            │                │
│ │             │   gcp_project_id=None,                                          │                │
│ │             │   ibmcloud_access_id=None,                                      │                │
│ │             │   ibmcloud_secret_key=None,                                     │                │
│ │             │   ibmcloud_iam_key=None,                                        │                │
│ │             │   ibmcloud_iam_endpoint=None,                                   │                │
│ │             │   ibmcloud_useragent=None,                                      │                │
│ │             │   ibmcloud_resource_group_id=None                               │                │
│ │             )                                                                 │                │
│ ╰───────────────────────────────────────────────────────────────────────────────╯                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'Invalid flag: default_azure_region'

```

**Environment info (please complete the following information):**
 - OS: [Mac OS]
- Python 3.11.3
- Skyplane 0.3.2

**Comment by maciej-wolny** [comment]
Resolved
